### ISSUE TITLE
[CLI][Bug] Schema defaults are not being set

### ISSUE THREAD

**Issue by pallabpain** [rapyuta-robotics/rapyuta-io-cli#152]
Encountered the following error while creating a package without the `runAsBash` field present in the manifest. It should have defaulted to `True`. But got this error instead.

```python
| Traceback (most recent call last):
|     <p0>/rio                            <module>        8: sys.exit(cli())
|     <distpkg>/click/core.py             __call__     1130: return self.main(*args, **kwargs)
|     <distpkg>/click/core.py             main         1055: rv = self.invoke(ctx)
|     <distpkg>/click/core.py             invoke       1657: return _process_result(sub_ctx.command.invoke(sub_ctx))
|     <distpkg>/click/core.py             invoke       1404: return ctx.invoke(self.callback, **ctx.params)
|     <distpkg>/click/core.py             invoke        760: return __callback(*args, **kwargs)
|     <distpkg>/riocli/apply/__init__.py  apply          63: rc.apply(dryrun=dryrun, workers=workers)
|     <distpkg>/riocli/apply/parse.py     apply          89: return self.apply_async(*args, **kwargs)
|     <distpkg>/riocli/apply/parse.py     apply_async   125: raise Exception(done_obj)
| Exception: runAsBash
```

#### How to reproduce?
Try applying the following manifest

```yaml
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: "nginx"
  version: "1.0.0"
spec:
  runtime: "device"
  device:
    arch: "amd64"
    restart: "always"
  executables:
    - name: "nginx"
      type: "docker"
      docker:
        image: "nginx" 
```

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1100231017)
