### ISSUE TITLE
[CI] Cleanup older comments when appimage is uploaded

### ISSUE THREAD

**Issue by pallabpain** [rapyuta-robotics/rapyuta-io-cli#171]
Every time an appimage is uploaded, the workflow posts a comment on the PR. Eventually, a lot of such comments pile up. We can consider removing older ones before posting the new comment via the workflow.

There are Github Actions available on the Marketplace that can help us do that: https://github.com/marketplace/actions/delete-comment

Here's an example:

```yaml
name: Delete comments from github-actions [bot]
on:
  workflow_dispatch:
jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}  # remove comments from the current PR

```

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1130198233)
